# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('number', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='answers/%Y/%m/%d/')),
                ('value', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1)),
                ('min_value', models.SmallIntegerField()),
                ('max_value', models.SmallIntegerField()),
                ('image', models.ImageField(upload_to='results/%Y/%m/%d/')),
                ('content', models.TextField()),
                ('is_excepted', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(upload_to='questions/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result',
            field=models.ManyToManyField(to='quiz.Result'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('question', 'number'), ('question', 'value')]),
        ),
    ]
