# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20160706_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 6, 13, 53, 5, 72892, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answers/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='answer',
            name='number',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 6, 13, 53, 56, 221377, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='value',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 6, 13, 54, 20, 146790, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answers/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='result',
            name='is_excepted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='max_value',
            field=models.SmallIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='min_value',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='quiz',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 6, 13, 54, 51, 545672, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='value',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='seq',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('question', 'value'), ('question', 'number')]),
        ),
    ]
